### ISSUE TITLE
Per-addon revenue cuts in a team

### ISSUE THREAD

**Issue by m0uka** [everyday-as/gmodstore-issues#1016] opened 2021-04-13 21:27 UTC
## Describe a feature you would like to have added to GmodStore
Please make a way to change the revenue cuts for each addon in one team.

Currently I have to create one team multiple times in order to have different revenue cuts for different addons, it would be much easier to just have one team for all our addons, and being able to change the revenue cut individually per addon. 
It is annoying to go to all my teams in order to make a sale for all my scripts, feature them, etc..

**Comment by TheodoorP** [comment] 2021-04-13 21:28
Duplicate of #677

**Closed by TheodoorP** 2021-04-13 21:28 UTC
Labels: 🌟 Feature
