### ISSUE TITLE
Blocked users cannot comment on user's resources 

### ISSUE THREAD

**Issue by nykez** [everyday-as/gmodstore-issues#987] opened 2021-02-09 23:57 UTC
## Describe a feature you would like to have added to GmodStore

Blocked users cannot comment on blocker's scripts (and other resources?.. jobs, etc)

**Comment by TheodoorP** [comment] 2021-02-10 07:48
Duplicate of #912. If you would like to comment on the matter please use that issue.

**Closed by TheodoorP** 2021-02-10 07:48 UTC
Labels: 🌟 Feature
