### ISSUE TITLE
Notification Disabling

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#871] opened 2020-04-27 22:04 UTC
## Describe a feature you would like to have added to GmodStore
A feature to disable notifications from an addon, this would allow you to click a button so you will receive no notifications from this addon if it is updated or anything else. To make it more usable, you could add options so you can select where you want to be notified of. This is useful because some addon authors publish a lot of small updates in a short time period and people don't wanna get spammed of this.

## Related attachments

**Comment by TheodoorP** [comment] 2020-12-03 17:46
Duplicate of #930

**Closed** 2020-12-03 17:47 UTC
