### ISSUE TITLE
Random Addon button

### ISSUE THREAD

**Issue by multiaudacity** [everyday-as/gmodstore-issues#1217] opened 2022-09-02 00:07 UTC
### Feature

A random Addon button similar to feeling lucky on Google along with a filter for unsupported and supported addons so you can see stuff that, while might be abandoned could still work fine and it's nice to have

**Comment by TheodoorP** [comment] 2022-09-02 06:29
Duplicate of #996

**Closed by TheodoorP** 2022-09-02 06:29 UTC
Labels: 🌟 Feature
