### ISSUE TITLE
Roadmap Sort Order

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#997] opened 2021-03-08 00:22 UTC
## Expected Behavior
Roadmap sorts in semantic order, 8.4, 8.5, 8.6

## Actual Behavior
8.4, 8.6, 8.5

## Steps to Reproduce the Problem

  1. Go to page
  2. Use eyes

## Specifications

  - GmodStore V: 8.3.49
  - Example URL: https://www.gmodstore.com/about/roadmap
  - Browser: Chrome

**Comment by TheodoorP** [comment] 2021-03-08 07:42
Duplicate of #993

**Closed by TheodoorP** 2021-03-08 07:42 UTC
Labels: 🐞 Bug
