### ISSUE TITLE
Notifications asking for you to review a recent purchase

### ISSUE THREAD

**Issue by TomDotBat** [everyday-as/gmodstore-issues#897] opened 2020-05-22 15:08 UTC
## Describe a feature you would like to have added to GmodStore
Add a notification that will be sent to the buyer x amount of days after purchasing an addon asking for a review. I believe it would be beneficial to the store as it will encourage more users to review addons and potentially bring in more sales for ones with many high ratings and such.

## Related attachments
N/a

**Comment by TheodoorP** [comment] 2020-05-22 15:13
Pretty much a duplicate of #701

**Closed by TheodoorP** 2020-05-22 15:13 UTC
