### ISSUE TITLE
New Update banner can't be removed

### ISSUE THREAD

**Issue by dotCore-off** [everyday-as/gmodstore-issues#1198] opened 2022-05-05 18:52 UTC
### Expected Behavior

New Update banner should get removed on purchased addons if we visit the addon's page / click on the new update banner directly / download latest version or any other relevant scenario.

### Actual Behavior

As of now, the new update banner remains whatever you try to do.
I'm unsure if this is intended, or if there's like a unique way to get rid of it, but I didn't find it yet.

### Reproduction Steps

```markdown
1. Go to Your Purchases page
2. Try to find an addon with a New Update banner
3. Visit the addon's page, versions or download latest files and notice that banner won't go away

Bonus. You might also notice New Update banners appearing on random addons
```

### Browsers

Firefox 100

### Example URL

https://www.gmodstore.com/users/dotcore/purchases

### GmodStore Version

v11.1.13

### Additional Information

This issue might be linked / affected by the following one: #1133.

**Comment by TheodoorP** [comment] 2022-05-05 20:56
Duplicate of #1133

**Closed by TheodoorP** 2022-05-05 20:56 UTC
Labels: 🐞 Bug
