### ISSUE TITLE
Better DLC highlighting / position

### ISSUE THREAD

**Issue by dotCore-off** [everyday-as/gmodstore-issues#1207] opened 2022-06-20 17:58 UTC
### Feature

On desktop version of the website, DLCs can be found at the bottom of the page.
Wouldn't it be more relevant to move it to the right column of the page w/ all addon information?
![image](https://user-images.githubusercontent.com/64563384/174656356-11acc896-d164-494c-93ac-e25ec888c81b.png)

### Additional Information

That'd make things easier for customers if they want to know about existing DLCs for an addon.
Additionally, you could do that as a carousel if there's multiple DLCs (to prevent ruining right column)

**Comment by TheodoorP** [comment] 2022-06-20 18:45
Duplicate of #514

**Closed by TheodoorP** 2022-06-20 18:45 UTC
Labels: 🌟 Feature
