### ISSUE TITLE
Can't search messages by SteamID64

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/gmodstore-issues#1267] opened 2023-07-24 18:55 UTC
### Expected Behavior

Messages filtered by SteamID64

### Actual Behavior

500 Internal Server Error

### Reproduction Steps

```markdown
Enter SteamID64 into search bar on messages page
```

### Browsers

Brave

### Example URL

https://www.gmodstore.com/messages?search=76561198173305878&sortby=newest

### GmodStore Version

v14.9.1

**Comment by TheodoorP** [comment] 2023-07-24 19:03
Seems to be caused by the UUID migration. Current behaviour is that it will search by user id instead of steam id.

**Comment by J0sh0nat0r** [comment] 2023-08-02 10:28
Fixed in v14.10.0

**Closed by J0sh0nat0r** 2023-08-02 10:28 UTC
Labels: 🐞 Bug
