### ISSUE TITLE
Minimum hours in Garry's Mod for buying addons

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#821] opened 2020-04-27 22:04 UTC
'## Describe a feature you would like to have added to GmodStore
This is something we had as a global limit previously. We no longer have it due to Steam's GDPR compliancy. They are now hiding games activity by default. We removed the feature not because of this, but because the API response was being cached for an undetermined amount of time, too long for users to bother registering.

This API no longer has said cache and if we implement it after registration, only upon buying it will be less annoying for a user, while possibly keeping creators safer.

**What would be the limitations/terms?**

- 100 hours global minimum
- Configurable per team, disabled by default
- Verified tick on a user whenever they have verified their Garry's Mod gametime
- Needs to affect both the user who's buying an addon, and whoever is being bought for (gifting)
- If buying items in the shopping cart, we have to remove items that require verification if the user is not verified (in the back-end, it's already prevented from being added in the front-end due to the previous point)

**How would the verification process work?**

- A job is automatically dispatched upon registration to check their Garry's Mod playtime. If their game details are public and they have 100+ hours, give them the verified tick immediately.
- If they are not verified we need to make a permanent notification at the top of the page that takes them to a page explaining why they are not verified. If they are not verified due to lack of playtime we can display their current amount of playtime with a % of how close they are to achieving verified status. If they are not verified due to a private profile/private game details we need to explain to them how to make it public. We only require it to be public during verification, afterwards it's fair game and the user's own choice.

## Related attachments
No

**Comment by TheodoorP** [comment] 2022-05-31 13:49
Going to mark this as a duplicate of #1060 due to the messages in there.

**Closed by TheodoorP** 2022-05-31 13:49 UTC
Labels: 🌟 Feature, Medium Priority
