### ISSUE TITLE
error making tickets

### ISSUE THREAD

**Issue by lalupaGaming** [everyday-as/gmodstore-issues#1234] opened 2023-01-08 14:00 UTC
### Expected Behavior

should make a ticket and say nothing is wrong

### Actual Behavior

i try to make a ticket but it doesnt and says  The body must not be empty
even with text inside the box

### Reproduction Steps

```markdown
1.
2.
3.
```

### Browsers

google chrome

### Example URL

everywhere, addon and website tickets 

### GmodStore Version

v12.5.0

**Comment by LastPlayerTR** [comment] 2023-01-08 14:04
https://github.com/everyday-as/gmodstore-issues/issues/1233

**Comment by TheodoorP** [comment] 2023-01-08 14:41
Duplicate of #1233

**Closed by TheodoorP** 2023-01-08 14:41 UTC
Labels: 🐞 Bug
