### ISSUE TITLE
Price w/ discount goes out of purchase box on bigger scales.

### ISSUE THREAD

**Issue by phixmeplease** [everyday-as/gmodstore-issues#1001] opened 2021-03-13 13:54 UTC
## Expected Behavior
The price scales to fit in the box.

## Actual Behavior
It goes out
![image](https://user-images.githubusercontent.com/59421259/111032325-9cfe8580-83d9-11eb-8c08-51a6bf925126.png)

## Steps to Reproduce the Problem

  1.  Scale up your page scale, I did it to 140%

## Specifications

  - GmodStore version (see footer): 8.4.4
  - Example url: https://www.gmodstore.com/
  - Browser: Brave/Chrome

**Comment by TheodoorP** [comment] 2021-04-08 12:07
Duplicate of #942

**Closed by TheodoorP** 2021-04-08 12:07 UTC
Labels: 🐞 Bug
