### ISSUE TITLE
Review submission rejected for "The rating field is required."

### ISSUE THREAD

**Issue by owainjones74** [everyday-as/gmodstore-issues#1132] opened 2021-11-30 16:11 UTC
### Expected Behavior

When submitting a review and completing the form, the review should be posted.

### Actual Behavior

The review is instead rejected with the error "The rating field is required.". Example: https://i.notgyazo.club/hXflem5TR.mp4

### Reproduction Steps

```markdown
1. Open the review modal.
2. Complete the form.
3. Submit the form.
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/market/view/noclip#add-review

### GmodStore Version

V10.2.26

### Additional Information

Could this be an issue with my Chrome extensions? I don't receive this behavior with any other form on the site.

**Comment by TheodoorP** [comment] 2021-11-30 16:12
Duplicate of #1127

**Closed by TheodoorP** 2021-11-30 16:12 UTC
Labels: 🐞 Bug

**Comment by owainjones74** [comment] 2021-11-30 16:14
Oh lol, my bad

**Comment by TheodoorP** [comment] 2021-11-30 16:14
No worries! :)
