### ISSUE TITLE
Move DLCs to underneath requirements on desktop

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/gmodstore-issues#1093] opened 2021-08-05 22:01 UTC
### Feature

Pls move DLCs from underneath reviews to underneath requirements on desktop

### Additional Information

https://www.gmodstore.com/market/view/billys-keypads

Advertising the DLC is pointless because it's at the very bottom of the page, and no one will look there

**Comment by Crap-Head** [comment] 2021-08-31 13:29
This is a duplicate of my issue https://github.com/everyday-as/gmodstore-issues/issues/514

**Closed** 2021-08-31 15:41 UTC
Labels: 🌟 Feature
